# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.operations_api import OperationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.operations_api.OperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_order(self):
        """Test case for cancel_order

        cancelOrder  # noqa: E501
        """
        pass

    def test_cancel_order_group(self):
        """Test case for cancel_order_group

        cancelOrderGroup  # noqa: E501
        """
        pass

    def test_edit_account_order(self):
        """Test case for edit_account_order

        editOrder  # noqa: E501
        """
        pass

    def test_get_account_metrics(self):
        """Test case for get_account_metrics

        getAccountMetrics  # noqa: E501
        """
        pass

    def test_get_market_data(self):
        """Test case for get_market_data

        getMarketData  # noqa: E501
        """
        pass

    def test_get_open_order_list(self):
        """Test case for get_open_order_list

        getOpenOrderList  # noqa: E501
        """
        pass

    def test_get_order_history_list(self):
        """Test case for get_order_history_list

        getOrderHistoryList  # noqa: E501
        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        getUserInfo  # noqa: E501
        """
        pass

    def test_open_account_order(self):
        """Test case for open_account_order

        placeOrder  # noqa: E501
        """
        pass

    def test_open_account_order_group(self):
        """Test case for open_account_order_group

        placeOrderGroup  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
