# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.market_api import MarketApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMarketApi(unittest.TestCase):
    """MarketApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.market_api.MarketApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_market_info(self):
        """Test case for get_market_info

        getMarketInfo  # noqa: E501
        """
        pass

    def test_get_order_book(self):
        """Test case for get_order_book

        getOrderBook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
