# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.edit_order_response import EditOrderResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestEditOrderResponse(unittest.TestCase):
    """EditOrderResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEditOrderResponse(self):
        """Test EditOrderResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.edit_order_response.EditOrderResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
