# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Body(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account': 'str',
        'event_types': 'MarketdataEventTypes',
        'symbols': 'list[str]'
    }

    attribute_map = {
        'account': 'account',
        'event_types': 'event_types',
        'symbols': 'symbols'
    }

    def __init__(self, account=None, event_types=None, symbols=None):  # noqa: E501
        """Body - a model defined in Swagger"""  # noqa: E501

        self._account = None
        self._event_types = None
        self._symbols = None
        self.discriminator = None

        if account is not None:
            self.account = account
        if event_types is not None:
            self.event_types = event_types
        if symbols is not None:
            self.symbols = symbols

    @property
    def account(self):
        """Gets the account of this Body.  # noqa: E501


        :return: The account of this Body.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this Body.


        :param account: The account of this Body.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def event_types(self):
        """Gets the event_types of this Body.  # noqa: E501


        :return: The event_types of this Body.  # noqa: E501
        :rtype: MarketdataEventTypes
        """
        return self._event_types

    @event_types.setter
    def event_types(self, event_types):
        """Sets the event_types of this Body.


        :param event_types: The event_types of this Body.  # noqa: E501
        :type: MarketdataEventTypes
        """

        self._event_types = event_types

    @property
    def symbols(self):
        """Gets the symbols of this Body.  # noqa: E501


        :return: The symbols of this Body.  # noqa: E501
        :rtype: list[str]
        """
        return self._symbols

    @symbols.setter
    def symbols(self, symbols):
        """Sets the symbols of this Body.


        :param symbols: The symbols of this Body.  # noqa: E501
        :type: list[str]
        """

        self._symbols = symbols

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
