# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CancelOrderGroupResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_responses': 'list[CancelOrderGroupResponseOrderResponses]'
    }

    attribute_map = {
        'order_responses': 'orderResponses'
    }

    def __init__(self, order_responses=None):  # noqa: E501
        """CancelOrderGroupResponse - a model defined in Swagger"""  # noqa: E501

        self._order_responses = None
        self.discriminator = None

        if order_responses is not None:
            self.order_responses = order_responses

    @property
    def order_responses(self):
        """Gets the order_responses of this CancelOrderGroupResponse.  # noqa: E501


        :return: The order_responses of this CancelOrderGroupResponse.  # noqa: E501
        :rtype: list[CancelOrderGroupResponseOrderResponses]
        """
        return self._order_responses

    @order_responses.setter
    def order_responses(self, order_responses):
        """Sets the order_responses of this CancelOrderGroupResponse.


        :param order_responses: The order_responses of this CancelOrderGroupResponse.  # noqa: E501
        :type: list[CancelOrderGroupResponseOrderResponses]
        """

        self._order_responses = order_responses

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CancelOrderGroupResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CancelOrderGroupResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
