# coding: utf-8

"""
    Broker API.

    the purpose of this application is to provide an application that is using plain go code to define an API  This should demonstrate all the possible comment annotations that are available to turn go code into a fully compliant swagger 2.0 spec. There are no TOS at this moment, use at your own risk we take no responsibility  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: support@cexbro.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class OpenOrderResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'order_id': 'int',
        'update_order_id': 'int'
    }

    attribute_map = {
        'order_id': 'orderId',
        'update_order_id': 'updateOrderId'
    }

    def __init__(self, order_id=None, update_order_id=None):  # noqa: E501
        """OpenOrderResponse - a model defined in Swagger"""  # noqa: E501

        self._order_id = None
        self._update_order_id = None
        self.discriminator = None

        if order_id is not None:
            self.order_id = order_id
        if update_order_id is not None:
            self.update_order_id = update_order_id

    @property
    def order_id(self):
        """Gets the order_id of this OpenOrderResponse.  # noqa: E501


        :return: The order_id of this OpenOrderResponse.  # noqa: E501
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this OpenOrderResponse.


        :param order_id: The order_id of this OpenOrderResponse.  # noqa: E501
        :type: int
        """

        self._order_id = order_id

    @property
    def update_order_id(self):
        """Gets the update_order_id of this OpenOrderResponse.  # noqa: E501


        :return: The update_order_id of this OpenOrderResponse.  # noqa: E501
        :rtype: int
        """
        return self._update_order_id

    @update_order_id.setter
    def update_order_id(self, update_order_id):
        """Sets the update_order_id of this OpenOrderResponse.


        :param update_order_id: The update_order_id of this OpenOrderResponse.  # noqa: E501
        :type: int
        """

        self._update_order_id = update_order_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OpenOrderResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OpenOrderResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
